using System.Xml.Linq;

namespace Yemekhane.UnitTests.Installer;

/// <summary>
/// Kurulum paketinin yeniden kurulabilir olmasini dogrular.
///
/// MajorUpgrade yalnizca surum numarasi ARTTIGINDA devreye girer. Ayni surumu tekrar kurmak
/// (bozulan dosyalari onarmak, basarisiz bir dagitimi yenilemek) Windows Installer tarafindan
/// 1638 "another version is already installed" ile reddedilir. Bu, sahada en sik karsilasilan
/// kurulum hatasidir ve kullaniciyi once elle kaldirmaya zorlar.
/// </summary>
public sealed class InstallerUpgradeTests
{
    private static readonly XNamespace Wxs = "http://wixtoolset.org/schemas/v4/wxs";

    [Fact]
    public void SameVersionCanBeReinstalledWithoutManualUninstall()
    {
        var upgrade = LoadPackage().Descendants(Wxs + "MajorUpgrade").Single();

        Assert.Equal("yes", (string?)upgrade.Attribute("AllowSameVersionUpgrades"));
    }

    [Fact]
    public void EachBuildGetsAFreshProductCodeSoReinstallIsAnUpgradeNotAReconfigure()
    {
        // ProductCode surume gore sabitlenirse, ayni surumu yeniden kurmak Windows Installer icin
        // "yeniden yapilandirma" olur ve PackageCode degistigi icin 1638 ile reddedilir --
        // MajorUpgrade/AllowSameVersionUpgrades mantigi hic calismaz. ProductCode="*" her derlemede
        // yeni bir kod uretir, boylece kurulum gercek bir upgrade olarak islenir.
        var script = File.ReadAllText(Path.Combine(FindRoot(), "scripts", "build-installer.ps1"));

        Assert.DoesNotContain("New-DeterministicGuid \"YemekhanePro.Product.", script, StringComparison.Ordinal);
    }

    [Fact]
    public void ProductCodeIsAutoGeneratedInThePackage()
    {
        var package = LoadPackage().Descendants(Wxs + "Package").Single();

        Assert.Equal("*", (string?)package.Attribute("ProductCode"));
    }

    [Fact]
    public void DowngradeIsBlockedWithATurkishMessage()
    {
        var upgrade = LoadPackage().Descendants(Wxs + "MajorUpgrade").Single();
        var message = (string?)upgrade.Attribute("DowngradeErrorMessage");

        Assert.False(string.IsNullOrWhiteSpace(message));
        Assert.Contains("YemekhanePro", message, StringComparison.Ordinal);
    }

    [Fact]
    public void UpgradeCodeIsStableSoUpgradesReplaceTheSameProduct()
    {
        // UpgradeCode degisirse her surum ayri urun olarak kurulur ve eskisi kaldirilmaz;
        // makinede yan yana birikirler.
        var package = LoadPackage().Descendants(Wxs + "Package").Single();

        Assert.False(string.IsNullOrWhiteSpace((string?)package.Attribute("UpgradeCode")));
    }

    [Fact]
    public void BuildScriptActuallyInstallsTheMsiNotJustExtractsIt()
    {
        // Administrative extraction (msiexec /a) MSI'nin acilabildigini gosterir ama kurulumun
        // calistigini GOSTERMEZ. 1638 "zaten yuklu" hatasi tam olarak bu bosluktan kacmisti.
        var script = File.ReadAllText(Path.Combine(FindRoot(), "scripts", "build-installer.ps1"));

        Assert.Contains("MSI kurulumu basarisiz oldu", script, StringComparison.Ordinal);
        Assert.Contains("Ayni surumun uzerine kurulum basarisiz oldu", script, StringComparison.Ordinal);
        Assert.Contains("MSI kaldirma basarisiz oldu", script, StringComparison.Ordinal);
    }

    [Fact]
    public void PackageShowsAWizardInsteadOfABareProgressBar()
    {
        // Arayuzsuz MSI cift tiklandiginda Windows "basic UI" moduna duser: yalnizca ilerleme
        // cubugu gosterir, ileri/ileri ekrani yoktur. perMachine oldugu icin UAC de isteyemez ve
        // Error 1925 ile sessizce iptal olur -- kullanici "bar doldu, bir sey olmadi" gorur.
        var document = LoadPackage();

        Assert.Contains(document.Descendants(), element => element.Name.LocalName == "WixVariable"
            || element.Name.LocalName == "ui" || element.Name.LocalName == "UIRef");
    }

    [Fact]
    public void BootstrapperExeExistsSoUsersGetAnInstallerTheyCanDoubleClick()
    {
        // MSI cift tiklamada UAC isteyemez; .exe bootstrapper yukseltmeyi kendisi ister.
        var bundle = Path.Combine(FindRoot(), "installer-bundle", "Bundle.wxs");

        Assert.True(File.Exists(bundle), "installer-bundle/Bundle.wxs bulunamadi: .exe kurulum paketi tanimli degil.");
        var document = XDocument.Load(bundle);
        Assert.Contains(document.Descendants(), element => element.Name.LocalName == "Bundle");
        Assert.Contains(document.Descendants(), element => element.Name.LocalName == "MsiPackage");
    }

    [Fact]
    public void BuildScriptProducesTheExeAlongsideTheMsi()
    {
        var script = File.ReadAllText(Path.Combine(FindRoot(), "scripts", "build-installer.ps1"));

        Assert.Contains("Yemekhane.Bundle.wixproj", script, StringComparison.Ordinal);
        Assert.Contains("YemekhanePro-Setup", script, StringComparison.Ordinal);
    }

    [Fact]
    public void InstalledFilesGoUnderProgramFilesAndDataStaysOut()
    {
        var document = LoadPackage();
        Assert.Contains(document.Descendants(Wxs + "StandardDirectory"),
            element => (string?)element.Attribute("Id") == "ProgramFiles6432Folder");
        Assert.DoesNotContain(document.Descendants(Wxs + "StandardDirectory"),
            element => (string?)element.Attribute("Id") == "LocalAppDataFolder");
    }

    [Fact]
    public void DesktopShortcutIsCreatedSoTheUserCanFindTheApp()
    {
        // Kullanici kurulumdan sonra uygulamayi masaustunde arar. Yalnizca Baslat menusu
        // kisayoluyla, program kurulmus ama "hicbir sey olmamis" gibi gorunur.
        var document = LoadPackage();
        var desktop = document.Descendants(Wxs + "StandardDirectory")
            .SingleOrDefault(element => (string?)element.Attribute("Id") == "DesktopFolder");

        Assert.NotNull(desktop);
        Assert.Contains(document.Descendants(Wxs + "Shortcut"),
            element => (string?)element.Attribute("Directory") == "DesktopFolder"
                || element.Parent?.Attribute("Directory")?.Value == "DesktopFolder");
    }

    [Fact]
    public void DesktopShortcutIsRemovedOnUninstall()
    {
        // Kaldirmadan sonra masaustunde calismayan bir kisayol kalmasi kullaniciyi yanilti.
        var component = LoadPackage().Descendants(Wxs + "Component")
            .Single(element => (string?)element.Attribute("Directory") == "DesktopFolder");

        Assert.Contains(component.Descendants(Wxs + "RegistryValue"),
            element => (string?)element.Attribute("KeyPath") == "yes");
    }

    [Fact]
    public void RenamedProductUsesItsOwnUpgradeCode()
    {
        // Urun adi degistiginde kurulum dizini de degisir. Eski UpgradeCode korunursa yeni
        // paket eskisini "upgrade" sayip kaldirmaya calisir; kullanici iki farkli isimle
        // yarim kurulmus bir sistemle kalir.
        var package = LoadPackage().Descendants(Wxs + "Package").Single();

        Assert.NotEqual("5D383CAC-54F8-47FD-AF1A-605E02F9D229", (string?)package.Attribute("UpgradeCode"));
    }

    private static XDocument LoadPackage() =>
        XDocument.Load(Path.Combine(FindRoot(), "installer", "Package.wxs"));

    private static string FindRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "Yemekhane.sln")))
            directory = directory.Parent;
        return directory?.FullName ?? throw new DirectoryNotFoundException("Solution root bulunamadı.");
    }
}
